### ISSUE TITLE
Sources don't play on Xbox One X

### ISSUE THREAD

**Issue by TaiDak** [Wilson-Magic/plugin.video.hummingbird#22]
Hey, I have an Xbox One X, and non of the sources are played, Hummingbird find them, but doesn't play them. I've tested the add-on on my computer, firestick, and Android TV, so I know it works. 

https://paste.kodi.tv/zisapayeva this is the log. Please tell me if it's the right log. I also understand if it's a problem that can't be fixed due to the limitations of the xbox, and thank you for the awesome add-on.

**Comment by Goldenfreddy0703** [comment]
Hey, umm sorry for bothering you man but Wilson has not responded to my issue but I will be glad to help you. Did you download the addon the old way where your go to file manager and put the url or did you go inside the kodi app data and put the files in there?

**Comment by TaiDak** [comment]
I used my own method, in which i downloaded the repo as a zip, then in kodi i set up my phone as source using ftp, and installed through zip, through my phone, the repo i mean.

**Comment by Goldenfreddy0703** [comment]
I kinda dont understand but I'm guessing you used the old way when going to install from zip file. Check if all the dependencies are installed or try to uninstall the addon and the dependencies that go with that addon and than install the addon again and maybe that should do it. If that doesn't work than this could be due to the xbox one development of kodi. I like the xbox one and I love that kodi got the approval to do this but it's hard to install everything on kodi when your on xbox one. I use a raspberry pi 4b with it's own kodi case and its remote and it was the best thing I ever bought, it was way better than a windows or an android device and I could transfer my old kodi files to my new one without any errors. Oh btw, if hummingbird is not working for you as much, there are other anime addons like WSBeta or Watchnixtoons. I do prefer hummingbird addon so much becouse of its art or where it gets it and how the episode are designed. I love everything about this addon. I just wish they could fix thier meta data on it and I also wish Wilson could reply too becouse he is amazing.

**Comment by Goldenfreddy0703** [comment]
Hey guess what, the addon doesn't work for me so that probably means it under maintenance at the moment but hey Wison could probably resolve this issue, I heard he is going to make some major updates for this addon in the future so dont worry.

**Comment by Wilson-Magic** [comment]
Hi I don't currently have Hummingbird set up on my Xbox. I will look into it.

@Goldenfreddy0703 Hi You have mentioned that I haven't responded to your issue. Sorry about that btw, had some irl stuff and been busy. What issue are you refering to?

**Comment by TaiDak** [comment]
Thank you man, just want to say you're incredible for doing this on your own, wish I know python so I could help

**Comment by Goldenfreddy0703** [comment]
Hey dont worry about my issue man but thank you so much for coming back, the only issue is mostly to fix fanart tv api and enabling fanart and that's about it.
